[2025-08-02T22:04:47.766+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-02T22:04:47.795+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_process_all_files_v1.move_users_file manual__2025-08-02T22:04:42.948706+00:00 [queued]>
[2025-08-02T22:04:47.807+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_process_all_files_v1.move_users_file manual__2025-08-02T22:04:42.948706+00:00 [queued]>
[2025-08-02T22:04:47.809+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-02T22:04:47.830+0000] {taskinstance.py:2330} INFO - Executing <Task(GCSToGCSOperator): move_users_file> on 2025-08-02 22:04:42.948706+00:00
[2025-08-02T22:04:47.846+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1138) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-02T22:04:47.848+0000] {standard_task_runner.py:63} INFO - Started process 1143 to run task
[2025-08-02T22:04:47.849+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'gcs_process_all_files_v1', 'move_users_file', 'manual__2025-08-02T22:04:42.948706+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/gcs_load_dag v2.py', '--cfg-path', '/tmp/tmptg8klvqk']
[2025-08-02T22:04:47.851+0000] {standard_task_runner.py:91} INFO - Job 49: Subtask move_users_file
[2025-08-02T22:04:47.951+0000] {task_command.py:426} INFO - Running <TaskInstance: gcs_process_all_files_v1.move_users_file manual__2025-08-02T22:04:42.948706+00:00 [running]> on host 06d424bf0ee1
[2025-08-02T22:04:48.100+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs_process_all_files_v1' AIRFLOW_CTX_TASK_ID='move_users_file' AIRFLOW_CTX_EXECUTION_DATE='2025-08-02T22:04:42.948706+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-02T22:04:42.948706+00:00'
[2025-08-02T22:04:48.104+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-02T22:04:48.121+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-08-02T22:04:48.129+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-08-02T22:04:49.372+0000] {gcs_to_gcs.py:534} INFO - Executing copy of gs://dataverse360-raw-data-rmk/landing/users_data.csv to gs://dataverse360-raw-data-rmk/raw/users_data.csv
[2025-08-02T22:04:49.593+0000] {gcs.py:261} INFO - Total Bytes: 164831 | Bytes Written: 164831
[2025-08-02T22:04:49.594+0000] {gcs.py:269} INFO - Object landing/users_data.csv in bucket dataverse360-raw-data-rmk rewritten to object raw/users_data.csv in bucket dataverse360-raw-data-rmk
[2025-08-02T22:04:49.595+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-02T22:04:49.617+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=gcs_process_all_files_v1, task_id=move_users_file, run_id=manual__2025-08-02T22:04:42.948706+00:00, execution_date=20250802T220442, start_date=20250802T220447, end_date=20250802T220449
[2025-08-02T22:04:49.713+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-02T22:04:49.738+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
